### ISSUE TITLE
 can not enable HTTPS protocol for web page

### ISSUE THREAD

**Issue by LVortex** [Tautulli/Tautulli-Docker#10]
after activation https - I get an error after reboot of service:
- WARNING :: MainThread : The pyOpenSSL module is missing. Install this module to enable HTTPS. HTTPS will be disabled.

I get this error if you use third-party certificates and create self-signed.
Info:
- Python 2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]
- Linux 4.4.59+ (#23739 SMP PREEMPT Tue Jul 10 00:18:17 CST 2018)
- Starting Tautulli v2.1.19-beta

Compose listing file:
##### Begin#####
version: '3.2'

services:

  tautulli:
    image: tautulli/tautulli:latest
    container_name: tautulli
    hostname: tautulli.local
    restart: on-failure:9
    networks:
      media-network:
        aliases:
          - tautulli.local
    ports:
    - "8181:8181"
    volumes:
      - ./config:/config
      - backups-docker:/backups
      - ./scripts:/scripts:ro
      - /volume1/Plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
      - ssl-cert-lets:/cert:ro
    environment:
      - TZ=Europe/Moscow
      - PUID=9339
      - PGID=65321
      - ADVANCED_GIT_BRANCH=beta

networks:
  media-network:
    external: true

volumes:
  ssl-cert-lets:
    external: true
  backups-docker:
    external: true
#####END#####

**Comment by JonnyWong16** [comment]
This is not a bug report. Please use the [Discord server](https://tautulli.com/discord) for support. 

You're missing the `pyopenssl` module.
