### ISSUE TITLE
Not updated with the latest version?

### ISSUE THREAD

**Issue by yegle** [Tautulli/Tautulli-Docker#22]
It looks like the image is not updated with the tautulli release. E.g. right now the latest version on docker was 2.1.28 and the latest is 2.1.29.

It might make sense to move this Dockerfile to the main repo so that a new version will be built with each commit, as long as stable release with each git tag.

**Comment by TheMeanCanEHdian** [comment]
Reboot the docker to update Tautulli. We are aware of the need to make changes regarding updates but this isn't a priority at this time.
