### ISSUE TITLE
The container doesn't use parameters passed to docker

### ISSUE THREAD

**Issue by Triqqo** [Tautulli/Tautulli-Docker#5]
While the readme mentions using parameters to configure Tautulli (such as specifying a port), the current setup with the s6-overlay and services.d doesn't allow this.

I propose a more standard approach using an `ENTRYPOINT` while still having the option to override the branch and repo URL using `-e` flags.

The modified Dockerfile I'm using myself is as follows:
```
FROM lsiobase/alpine.python:3.6

# install packages
RUN \
 apk add --no-cache --virtual=build-dependencies \
	g++ \
	gcc \
	make \
	python-dev && \
# install pycryptodomex Plexapi
 pip install --no-cache-dir -U \
	pycryptodomex plexapi && \
# cleanup
 apk del --purge \
	build-dependencies && \
 rm -rf \
	/root/.cache

ENV ADVANCED_GIT_BRANCH="master"
ENV ADVANCED_GIT_REPO="https://github.com/tautulli/tautulli.git"

COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]
```
With `entrypoint.sh` containing:
```
#!/usr/bin/env bash

[[ ! -d "/opt/plexpy/.git" ]] && \
	git clone --branch $ADVANCED_GIT_BRANCH $ADVANCED_GIT_REPO /opt/plexpy

python /opt/plexpy/PlexPy.py --datadir /config "$@"
```

Any args after `docker run <image>` or in docker-compose's `command:` definition will be passed to the entrypoint.

**Comment by TheMeanCanEHdian** [comment]
Can you elaborate on how you are having issues with this? I can set a port using `-p` just fine in `docker run` so I am unclear on what you are saying your issue is.

**Comment by Triqqo** [comment]
I’m not talking about Docker’s portmapping, but rather Tautulli’s commandline args. Normally when you start Tautulli you’re able to run `PlexPy.py —port 80` to for example run it on port 80. Ideally you could do the same with Docker like `docker run tautulli —port 80` as any args after the image name will be passed to the entrypoint (as opposed to before the image name, which are just docker’s own options). The same goes for any other commandline options.

**Comment by TheMeanCanEHdian** [comment]
I'm not sure I see a scenario where specifying commandline arguments is something that is needed for the container. Specifying the internal port that Tautulli runs on, for example, is of little consequence when you have the ability to set a unique external one on the container.

**Comment by wcomartin** [comment]
What is the benefit of this vs using dockers built in port mapping

**Comment by TheMeanCanEHdian** [comment]
At this time this is expected behavior. This issue can be reopened if there is a convincing argument for why you would use environment variables over `docker run` parameters.
